# Generated by Django 2.2.3 on 2019-07-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0003_auto_20190718_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='title',
            field=models.CharField(default='Без названия.', max_length=150),
        ),
    ]
