# Generated by Django 2.2.3 on 2019-07-18 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0004_poem_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='text',
        ),
        migrations.RemoveField(
            model_name='poem',
            name='username',
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(default='Анон', max_length=50)),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poems.Poem')),
            ],
        ),
    ]
